version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PASSWORD=ZSLOydF0YfIAjXJQ79EvRsTtn
      - REDIS_PASSWORD=NIAGpKcoUYDdSrPsRv4ZOgHE6
      - JWT_SECRET=x9hatue1n367sokgwjvzdiryfq502c8bpml4
      - ENCRYPTION_KEY=jcmpqny5ig1uor9tk67zva0f3wxel8ds4b2h
    depends_on:
      - mysql
      - redis
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: reved_kids
      MYSQL_USER: reved_user
      MYSQL_PASSWORD: ZSLOydF0YfIAjXJQ79EvRsTtn
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass NIAGpKcoUYDdSrPsRv4ZOgHE6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
