services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=reved_user
      - DB_PASSWORD=reved_password
      - DB_NAME=reved_kids
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET:-default-jwt-secret-for-development-only}
      - JWT_EXPIRES_IN=24h
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-default-encryption-key-for-development-only}
      - RATE_LIMIT_MAX=100
      - RATE_LIMIT_WINDOW=900000
      - ENABLE_METRICS=true
      - CACHE_TTL=900
      - REQUEST_TIMEOUT=30000
      - BODY_LIMIT=10485760
      - CORS_ORIGIN=http://localhost:3000,http://localhost:3001
      - LOG_LEVEL=info
    depends_on:
      - mysql
      - redis
    volumes:
      - uploads:/app/uploads
    restart: unless-stopped
    networks:
      - reved-kids

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: reved_kids
      MYSQL_USER: reved_user
      MYSQL_PASSWORD: reved_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - reved-kids

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - reved-kids
    command: redis-server --appendonly yes

volumes:
  mysql_data:
  redis_data:
  uploads:

networks:
  reved-kids:
    driver: bridge
